version: 2

builds:
  - main: ./cmd/piperig
    binary: piperig
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz

brews:
  - repository:
      owner: joarhal
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/joarhal/piperig"
    description: "Declarative pipeline runner for shell scripts"
    license: "MIT"
    test: |
      system "#{bin}/piperig", "version"

changelog:
  use: github
  filters:
    exclude:
      - "^docs"
      - "^chore"
      - "^test"
