#!/bin/bash

# Colors
RESET="\033[0m"
BOLD="\033[1m"
DIM="\033[2m"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
CYAN="\033[36m"
WHITE="\033[37m"

echo ""
echo -e "${BOLD}${WHITE}→ scripts/resize.py  date=2026-03-18  size=1920x1080  label=fullhd${RESET}"
echo -e "  ${DIM}·${RESET} ${DIM}Resizing image...${RESET}"
echo -e "  ${CYAN}▸${RESET} ${CYAN}fullhd | photo_001.jpg | 1920x1080${RESET}"
echo -e "  ${DIM}·${RESET} ${DIM}Applying sharpening filter...${RESET}"
echo -e "  ${CYAN}▸${RESET} ${CYAN}fullhd | photo_001.jpg | sharpened${RESET}"
echo -e "  ${YELLOW}!${RESET} ${YELLOW}Warning: EXIF data missing${RESET}"
echo -e "  ${DIM}·${RESET} ${DIM}Done${RESET}"
echo -e "${GREEN}✓${RESET} ${BOLD}scripts/resize.py${RESET}  ${DIM}0.8s${RESET}"

echo ""
echo -e "${BOLD}${WHITE}→ scripts/resize.py  date=2026-03-18  size=1280x720  label=hd${RESET}"
echo -e "  ${DIM}·${RESET} ${DIM}Resizing image...${RESET}"
echo -e "  ${YELLOW}!${RESET} ${YELLOW}Connection timeout${RESET}"
echo -e "  ${YELLOW}↻${RESET} ${YELLOW}retry 1/3 (1s)${RESET}"
echo -e "  ${DIM}·${RESET} ${DIM}Resizing image...${RESET}"
echo -e "  ${CYAN}▸${RESET} ${CYAN}hd | photo_001.jpg | 1280x720${RESET}"
echo -e "  ${DIM}·${RESET} ${DIM}Done${RESET}"
echo -e "${GREEN}✓${RESET} ${BOLD}scripts/resize.py${RESET}  ${DIM}1.4s${RESET}"

echo ""
echo -e "${BOLD}${WHITE}→ scripts/upload.sh  bucket=s3://photos-processed${RESET}"
echo -e "  ${DIM}·${RESET} ${DIM}Uploading 8 files...${RESET}"
echo -e "  ${YELLOW}!${RESET} ${YELLOW}S3 throttling${RESET}"
echo -e "  ${YELLOW}↻${RESET} ${YELLOW}retry 1/3 (1s)${RESET}"
echo -e "  ${YELLOW}!${RESET} ${YELLOW}S3 throttling${RESET}"
echo -e "  ${YELLOW}↻${RESET} ${YELLOW}retry 2/3 (1s)${RESET}"
echo -e "  ${YELLOW}!${RESET} ${YELLOW}S3 throttling${RESET}"
echo -e "  ${YELLOW}↻${RESET} ${YELLOW}retry 3/3 (1s)${RESET}"
echo -e "  ${YELLOW}!${RESET} ${YELLOW}S3 throttling${RESET}"
echo -e "${RED}✗${RESET} ${BOLD}scripts/upload.sh${RESET}  ${RED}exit=1${RESET}  ${DIM}4.1s${RESET}"
echo ""
