#!/bin/bash

RESET="\033[0m"
BOLD="\033[1m"
DIM="\033[2m"
CYAN="\033[36m"
GREEN="\033[32m"
WHITE="\033[37m"
INVERSE="\033[7m"

echo ""
echo -e "  ${BOLD}piperig run${RESET}                                          ${INVERSE}${BOLD} run ${RESET} ${DIM}check${RESET}  ${DIM}←/→${RESET}"
echo ""
echo -e "  ${INVERSE}${BOLD} pipelines/daily/images.pipe.yaml ${RESET}  ${DIM}— Resize images for the last 2 days${RESET}"
echo -e "  ${WHITE} pipelines/daily/reports.pipe.yaml ${RESET}  ${DIM}— Weekly sales report${RESET}"
echo -e "  ${WHITE} pipelines/daily/sync.pipe.yaml ${RESET}  ${DIM}— Sync data from S3${RESET}"
echo -e "  ${CYAN} pipelines/daily/${RESET}"
echo -e "  ${WHITE} pipelines/maintenance/backup.pipe.yaml ${RESET}  ${DIM}— Database backup${RESET}"
echo -e "  ${WHITE} pipelines/maintenance/cleanup.pipe.yaml ${RESET}  ${DIM}— Remove old temp files${RESET}"
echo -e "  ${CYAN} pipelines/maintenance/${RESET}"
echo -e "  ${WHITE} pipelines/deploy/staging.pipe.yaml ${RESET}  ${DIM}— Deploy to staging${RESET}"
echo -e "  ${WHITE} pipelines/deploy/production.pipe.yaml ${RESET}  ${DIM}— Deploy to production${RESET}"
echo -e "  ${CYAN} pipelines/deploy/${RESET}"
echo -e "  ${CYAN} pipelines/${RESET}"
echo ""
echo -e "  ${DIM}↑/↓ move  •  ←/→ mode  •  type to filter  •  Enter run  •  q quit${RESET}"
echo ""
echo ""
echo -e "  ${DIM}--- check mode: ---${RESET}"
echo ""
echo ""
echo -e "  ${BOLD}piperig run${RESET}                                          ${DIM}run${RESET}  ${INVERSE}${BOLD} check ${RESET}  ${DIM}←/→${RESET}"
echo ""
echo -e "  ${INVERSE}${BOLD} pipelines/daily/images.pipe.yaml ${RESET}  ${DIM}— Resize images for the last 2 days${RESET}"
echo -e "  ${WHITE} pipelines/daily/reports.pipe.yaml ${RESET}  ${DIM}— Weekly sales report${RESET}"
echo -e "  ${WHITE} pipelines/daily/sync.pipe.yaml ${RESET}  ${DIM}— Sync data from S3${RESET}"
echo -e "  ${CYAN} pipelines/daily/${RESET}"
echo -e "  ${WHITE} pipelines/maintenance/backup.pipe.yaml ${RESET}  ${DIM}— Database backup${RESET}"
echo -e "  ${WHITE} pipelines/maintenance/cleanup.pipe.yaml ${RESET}  ${DIM}— Remove old temp files${RESET}"
echo -e "  ${CYAN} pipelines/maintenance/${RESET}"
echo -e "  ${WHITE} pipelines/deploy/staging.pipe.yaml ${RESET}  ${DIM}— Deploy to staging${RESET}"
echo -e "  ${WHITE} pipelines/deploy/production.pipe.yaml ${RESET}  ${DIM}— Deploy to production${RESET}"
echo -e "  ${CYAN} pipelines/deploy/${RESET}"
echo -e "  ${CYAN} pipelines/${RESET}"
echo ""
echo -e "  ${DIM}↑/↓ move  •  ←/→ mode  •  type to filter  •  Enter check  •  q quit${RESET}"
echo ""
